export * from './genresDto.interface';
export * from './genreGenresDto.interface';
export * from './moviesCredits.interface';
export * from './movieVideo.interface';
export * from './movieVideoDto.interface';
export * from './genreIMovie.inteface';
export * from './movie.inteface';
export * from './movieDto.inteface';
export * from './movieImages.interface';
